# https://docs.haskellstack.org/en/stable/travis_ci/

language: generic
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

addons:
  apt:
    packages:
      - haskell-stack

os: linux

dist: bionic

env:
  - PACKAGE=.
  - PACKAGE=opentracing
  - PACKAGE=opentracing-cloudtrace
  - PACKAGE=opentracing-examples
  - PACKAGE=opentracing-http-client
  - PACKAGE=opentracing-jaeger
  - PACKAGE=opentracing-wai
  - PACKAGE=opentracing-zipkin-common
  - PACKAGE=opentracing-zipkin-v1
  - PACKAGE=opentracing-zipkin-v2

script:
  - export DIR=~/.local/bin
  - if [ ! -d "$DIR" ]; then mkdir -p $DIR; fi
  - stack upgrade
  - hash -r
  - cd $PACKAGE
  - stack setup
  - stack build
  - stack test
